// <auto-generated />
using System;
using CoffeeSeeu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeSeeu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116071902_AddOrdersAndOrderItems")]
    partial class AddOrdersAndOrderItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeSeeu.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Không gian ấm cúng, gần gũi",
                            Name = "Không gian quán"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Những người pha chế tài năng",
                            Name = "Đội ngũ"
                        });
                });

            modelBuilder.Entity("CoffeeSeeu.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Description = "Góc chill tầng 1",
                            ImagePath = "/img/shop-1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            Description = "Không gian sân thượng",
                            ImagePath = "/img/shop-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 1,
                            Description = "Không gian đọc sách",
                            ImagePath = "/img/shop-3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 2,
                            Description = "Minh Anh",
                            ImagePath = "/img/staff-1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 2,
                            Description = "Tuấn Kiệt",
                            ImagePath = "/img/staff-2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 2,
                            Description = "Hồng Nhung",
                            ImagePath = "/img/staff-3.jpg"
                        });
                });

            modelBuilder.Entity("CoffeeSeeu.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeSeeu.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CoffeeSeeu.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cà phê nguyên chất, vị chua nhẹ",
                            ImageUrl = "/img/products/blubery-Matcha_Late.jpg",
                            Name = "Cà phê hạt Arabica",
                            Price = 120000m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            Description = "Đậm vị, thơm lâu",
                            ImageUrl = "/img/products/cookies.jpg",
                            Name = "Cà phê hạt Robusta",
                            Price = 95000m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thức uống truyền thống Việt Nam",
                            ImageUrl = "/img/products/hot-cacao.jpg",
                            Name = "Cà phê sữa đá",
                            Price = 45000m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cà phê rang xay sẵn, tiện pha",
                            ImageUrl = "/img/products/mango-machiato.jpg",
                            Name = "Cà phê pha phin",
                            Price = 55000m,
                            Rating = 3
                        });
                });

            modelBuilder.Entity("CoffeeSeeu.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "/img/default-avatar.png",
                            Email = "admin@coffeeseeu.com",
                            Password = "AQAAAAIAAYagAAAAEEWNb0NW6F3YvJTwH0UqFVDaUXbk1lgF1Y47VKyM+E2lwJweaYv2vHFets9vwuah1A==",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CoffeeSeeu.Models.Image", b =>
                {
                    b.HasOne("CoffeeSeeu.Models.Album", "Album")
                        .WithMany("Images")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("CoffeeSeeu.Models.OrderItem", b =>
                {
                    b.HasOne("CoffeeSeeu.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeeSeeu.Models.Album", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("CoffeeSeeu.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
